apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: ciaran
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/url-shortener
            - name: SPRING_DATASOURCE_USERNAME
              value: ciaran
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          image: ciarantone/docker-spring-boot-postgres:latest
          name: app
          ports:
            - containerPort: 5422
              protocol: TCP
      restartPolicy: Always
