services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=ciaran
      - POSTGRES_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/url-shortener
      - SPRING_DATASOURCE_USERNAME=ciaran
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "5422:5422"

  react-app:
    container_name: frontend
    build:
      context: "./Url-Frontend"
      dockerfile: Dockerfile
    ports:
      - "3001:3000"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=ciaran
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=url-shortener
    ports:
      - "5432:5432"