services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=ciaran
      - POSTGRES_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/url-shortener
      - SPRING_DATASOURCE_USERNAME=ciaran
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    networks:
      - app-network

  react-app:
    container_name: frontend
    build:
      context: "C:/Users/CiaranTone/Url-Frontend"
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=ciaran
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=url-shortener
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
